# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
    ]
