# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0002_course_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('SCI', 'Science'), ('BIZ', 'Business'), ('DES', 'Design'), ('UN', 'Uncategorized')], default='UN', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='l1r4group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
