# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0003_auto_20170322_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('SCI', 'Science'), ('BIZ', 'Business'), ('DES', 'Design')], max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.CharField(choices=[('SP', 'Singapore Polytechnic'), ('NYP', 'Nanyang Polytechnic'), ('NP', 'Ngee Ann Polytechnic'), ('RP', 'Republic Polytechnic'), ('TP', 'Temasek Polytechnic')], max_length=3),
        ),
    ]
