# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0005_auto_20170322_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('SCI', 'Science'), ('BIZ', 'Business'), ('DES', 'Design')], max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='l1r4group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.CharField(choices=[('SP', 'Singapore Polytechnic'), ('NYP', 'Nanyang Polytechnic'), ('NP', 'Ngee Ann Polytechnic'), ('RP', 'Republic Polytechnic'), ('TP', 'Temasek Polytechnic')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='L1R4Group',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
