# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0007_auto_20170324_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
    ]
