# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0010_auto_20170324_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=0, max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
