# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0013_auto_20170325_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.IntegerField(default=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
