# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0014_auto_20170325_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('SCI', 'Science'), ('BIZ', 'Business'), ('IT', 'IT'), ('MED', 'Design & Media'), ('HSS', 'Humanities'), ('ENV', 'Environment'), ('HEA', 'Health'), ('MAR', 'Maritime')], max_length=3),
        ),
    ]
