# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0015_auto_20170326_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B3'), (4, 'B4'), (5, 'C5'), (6, 'C6'), (7, 'D7'), (8, 'E8'), (9, 'F9')], max_length=2),
        ),
    ]
