# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0017_auto_20170402_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('A1', 1), ('A2', 2), ('B3', 3), ('B4', 4), ('C5', 5), ('C6', 6), ('D7', 7), ('E8', 8), ('F9', 9)], max_length=2),
        ),
    ]
