# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0018_auto_20170402_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='l1r4_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='l1r4_B',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='l1r4_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='l1r4_D',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B3'), (4, 'B4'), (5, 'C5'), (6, 'C6'), (7, 'D7'), (8, 'E8'), (9, 'F9')], max_length=2),
        ),
    ]
