# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0019_auto_20170405_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='targets',
            field=models.ManyToManyField(to='coursesearch.Course'),
        ),
    ]
