# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0020_profile_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='targets',
        ),
    ]
