# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesearch', '0022_auto_20170405_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='related',
            field=models.TextField(blank=True),
        ),
    ]
